# Generated by Django 5.0.2 on 2024-03-01 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_remove_companyjobs_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='job_location',
        ),
    ]
